### ISSUE TITLE
Relation with comercial ACSI2STM?

### ISSUE THREAD

**Issue by EUcitizen** [retro16/acsi2stm#23]
There is project sold with same name "ACSI2STM": https://www.atari-forum.com/viewtopic.php?t=40018

How is relation with this open source project? Is use of name authorised? Is use of same software authorised?

PS: I like open source project better. 😄

**Comment by retro16** [comment]
I had a few people asking if they could build and sell some units, but I don't know if this particular project is one of them.

However, this is not an issue: my project is covered by the GPLv3 license. It means that anyone can use the code without permission (and sell products based on it), but they *must* provide the source code (including their modifications) with the units they sell: either with the unit itself, or a link to download it. This is a legal requirement of the GPL license.

The name ACSI2STM is not protected so it's fine that they use it.

Here is my personal opinion about people selling products based on my code:

* This is super cool, I feel honored that my work can be useful to some people and I really like it.
* Some sellers actually helped me to improve the code, so big thanks to them.
* Sellers should not expect this code to work flawlessly. They are responsible for supporting the products they sell.
* Feedback on this github is highly appreciated. I take any bug/improvement submission seriously and do the best I can in my very limited free time.
* Of course, any patch/pull request is welcome, especially from sellers that have feedback from many users with many different machines.
* I am very attached to the GPLv3 license. Sellers/modders really have to provide the source code, especially if they modified it.

**Comment by EUcitizen** [comment]
Thank you for clarification. Particular last sentence.

Seller writes in forum "Original firmware is slightly optimized". But does not provide source code for optimized firmware.

**Comment by peterdenmarkSeest** [comment]
Greetings

As a customer of the seller you pointed,

Be polite and ask, did you try a "please"?
You will be regarded with this:

Line 54: #define CSA1_MASK 0b11000000 //Remove an "and" operation

Line 332: while((b = GPIOB->regs->IDR) & (CSA1_MASK)); //Remove watchdog feeding

All customers know that the software is from Jean-Matthieu Coulon,
In the package there is an instructions sheet, as second sentence it reads:

-This devices uses the code from ACSI2STM: Jean-Matthieu COULON, give thanks to him!


Also, we know that one of these manufactured devices were delivered freely to Coulon,

and more important, I ordered one of these for my stfm and ste computers.
It worked ok for STFM, but not in ste. After several attempts, the manufactured developed a custom firmware exclusive to me, and it works well in the ste.

Due to I am the type of person that bought from many sellers, also have an UltraSatan, that never worked in the ste.
And no solutions were provided, as well I bought one from this seller:

https://www.ebay.es/itm/154897663589?hash=item24109ec665:g:sP4AAOSwhjFhWf6Z

The funny part is it does not work in the ste, but the seller you pointed wrote freely a firmware that supports the 2 sd cards of SD4ST. A device the pointed seller is not the manufacturer, but provided help and solutions for it.


Recently I bought 2 more units, surprisingly its a new design, that operates faster. Works well in stfm and ste.

According to the seller, the faster operation relies in careful sd card lines, letting higher sd frequencies.

**Comment by EUcitizen** [comment]
Paper saying "thanks" is not sufficient for GPLv3.

Also, can it be that you are in fact the seller of comercial ACSI2STM, @[peterdenmarkSeest](https://github.com/peterdenmarkSeest)?

**Comment by retro16** [comment]
I don't want to upset anyone. Now I recall who is the guy, I confirm that he is super cool, he sent me a free piece (nice product BTW) and was super helpful with feedback and ideas. I also appreciate that he gives credits to me. I also owe him an apology for changing the pinout for v2 a few weeks after he released his product !

That being said, I still confirm that the code is GPLv3 for a reason: I want my code as well as other people's improvements to be shared and improved by a community. Giving a patch of 2 lines with a description of the changes is *not* the full sources. Being polite when asking for the sources is not legally required, but I strongly encourage it !

That also applies to any "custom" version relying partially or totally on my code. And it's not just about me, it's also about the patched Arduino library I included in the old version 1 of acsi2stm.
