### ISSUE TITLE
4.0c firmware missing SHIFT+S

### ISSUE THREAD

**Issue by mamejay** [retro16/acsi2stm#40]
Hello again.  I have been testing the SHIFT+S with the latest firmware but it seems to go straight into GEM.
I have no issues with previous firmware.  Has this been omitted?

Also a strange observation.  I have a lot of Blue pills that pass a blink test but would not work at all with firmwares up to 3.  I decided to just try 4.0c and they have now come to life.  Not sure what you did but they seem to be working now which is wonderful as I have a bunch of these which I thought were duds.

Anyway let me know about the Shift+S functionality .
Thanks!

**Comment by retro16** [comment]
Hello again.

My old driver, including the setup tool, was removed from 4.0 as it should become 100% useless, and flash space on the STM32 is taken by the new GemDrive driver.

Useful functionality (self-tests and clock setup) will be migrated to regular TOS executables that you can run from the ST desktop (from a floppy or from within the ACSI2STM itself). Partitioning tools will become obsolete as GemDrive requires a PC-formated SD card with a single partition (including support for ExFAT) so just use Windows or whatever PC formating tool for that.
4.0c is still in alpha state, and self-tests are long to write and debug, but I think that it will bring the rock solid operation ACSI2STM desperately needs.

If you have objections against the complete removal of the setup tool, I am always very interested in constructive feedback. Please list what features are useful to you, and how you use it. Can't guarantee that I can bring it back, but I will try my best to fulfill your use cases.

About your Blue Pills working, it's part of that STM32 hardware bug I worked around. Thank you so much for this feedback, it's really important to me because that hardware issue is really semi-random in the worst possible way: when changing code and recompiling, one batch may become good and another may become bad, randomly, without apparent reason. My workaround fixed all the Blue Pills I own, but you never know if there isn't another quirky batch, so the more feedback I have, the more confident I can be in my low level DMA routines.
